name: Regular Update

on:
  workflow_dispatch:
  schedule:
    - cron: '3/12 * * * *'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.6'
    
      - name: Install python packages
        run: pip install -r actions_requirements.txt

      - name: Login
        id: login
        run: python3 foundation/login.py --cookie=${{ secrets.EAISESS }} --uid="${{ secrets.NJU_USERNAME }}" --pwd="${{ secrets.NJU_PASSWORD }}" --github
      
      - name: Record electricity
        env:
          TZ: "Asia/Hong_Kong"
        run: python3 electricity/elec-monitor.py --room=${{ secrets.ELEC_ROOM }} --key=${{ steps.login.outputs.logincookie }}
      
      - name: Recharge campus card & Internet account
        env:
          TZ: "Asia/Hong_Kong"
        run: _TG_BOT_TOKEN=${{ secrets.TG_BOT_TOKEN }} _TG_CHAT_ID=${{ secrets.TG_CHAT_ID }} python3 balance/balance.py --recharge-parameter=${{ secrets.CARD_RECHARGE }} --key=${{ steps.login.outputs.logincookie }} 
      
      - name: Commit files
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Actions Updater"
          git add -A
          git commit -m "Actions: Update electricity data" -a
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
